Django5/Django5/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from userapp import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^userapp/', include('userapp.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'special/', views.special, name='special'),
]

Django5/userapp/urls.py
from django.conf.urls import url
from userapp import views

# Template URLS
app_name = 'userapp'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

Django5/userapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

Django5/userapp/forms.py
from django import forms
from django.contrib.auth.models import User
from userapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

Django5/userapp/views.py
from django.shortcuts import render
from userapp.forms import UserForm, UserProfileInfoForm

# login imports
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    return render(request, 'userapp/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return render(request, 'userapp/special.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'userapp/registration.html', {
        'user_form':user_form, 'profile_form':profile_form, 'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account Not Active.')

        else:
            print('Someone tried to login and failed.')
            print('Username was {} and password was {}'.format(username, password))
            return HttpResponse('Invalid login details supplied.')

    else:
        return render(request, 'userapp/login.html', {})

Django5/templates/userapp/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'userapp:register' %}">Register</a></li>
                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'userapp:user_login' %}">Login</a></li>
                {% endif %}
                <li><a class="navbar-link" href="{% url 'special' %}">Special</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
{% block body_block %}
{% endblock %}
    </div>

</body>
</html>

Django5/templates/userapp/index.html
{% extends "userapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five!</h1>
</div>

{% endblock %}

Django5/templates/userapp/login.html
{% extends "userapp/base.html" %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'userapp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Enter Password">

        <input type="submit" name="" value="Login">
    </form>
</div>

{% endblock %}

Django5/templates/userapp/registration.html
{% extends "userapp/base.html" %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering with Django Level Five!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register!">
    </form>
    {% endif %}
</div>

{% endblock %}

Django5/templates/userapp/special.html
{% extends "userapp/base.html" %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron" align="center">
    <h2>Members Special Page.</h2>
    <img class="boximg" src="{% static "images/djangomovie.jpg" %}" alt="No joy here.">
</div>

{% endblock %}